feat(bouncer): MDBX persistence + hold fixes + adaptive connect count
Bouncer sessions now persist across server restarts via MDBX:
- New FEAT_BOUNCER_PERSIST flag (default off) enables persistence
- Sessions stored in bouncer_sessions DBI within metadata env
- Ghosts restored to channels on startup before listeners open
- Adaptive hold timer uses remaining time, not full hold duration

Hold bug fixes:
- packet.c: Check IsBouncerHold before exit_client in client_dopacket
- s_bsd.c: Guard hold check for already-held clients (EOF after QUIT)
- Restore path uses adaptive hold time, not BOUNCER_MAX_HOLD

Adaptive hold now counts all connections (hs_connect_count):
- Resumes from HOLDING + shadow attaches both contribute
- Rewards always-on setups with mobile shadow connections
- BOUNCER_DB_VERSION bumped to 2 (old records discarded)

Docker build optimization:
- Multi-stage parallel library builds (libkc, libmdbx)
- ccache via BuildKit cache mount
- Separate configure stage for better layer caching
- GeoIP database included in runtime image

Co-Authored-By: Claude Opus 4.5 <noreply@anthropic.com>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -642,6 +642,7 @@ ac_includes_default="\
 ac_header_c_list=
 ac_subst_vars='LTLIBOBJS
 LIBOBJS
+PKG_CONFIG
 DPATH
 IRCDGRP
 IRCDOWN
@@ -1411,7 +1412,7 @@ Optional Features:
   --disable-ssl           Disable Secure Sockets Layer support
   --disable-geoip         Disable GeoIP support
   --disable-mmdb         Disable MaxMindDB support
-  --disable-mdbx          Disable libmdbx for storage support
+  --disable-mdbx          Disable libmdbx storage support
   --disable-zstd          Disable zstd compression support
   --disable-keycloak      Disable Keycloak (libkc) support
 
@@ -8756,6 +8757,98 @@ fi
 printf "%s\n" "$unet_cv_enable_mmdb" >&6; }
 
 if test x"$unet_cv_enable_mmdb" = xyes; then
+    if test "x$PKG_CONFIG" = x; then
+    # Extract the first word of "pkg-config", so it can be a program name with args.
+set dummy pkg-config; ac_word=$2
+{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for $ac_word" >&5
+printf %s "checking for $ac_word... " >&6; }
+if test ${ac_cv_path_PKG_CONFIG+y}
+then :
+  printf %s "(cached) " >&6
+else case e in #(
+  e) case $PKG_CONFIG in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_PKG_CONFIG="$PKG_CONFIG" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  case $as_dir in #(((
+    '') as_dir=./ ;;
+    */) ;;
+    *) as_dir=$as_dir/ ;;
+  esac
+    for ac_exec_ext in '' $ac_executable_extensions; do
+  if as_fn_executable_p "$as_dir$ac_word$ac_exec_ext"; then
+    ac_cv_path_PKG_CONFIG="$as_dir$ac_word$ac_exec_ext"
+    printf "%s\n" "$as_me:${as_lineno-$LINENO}: found $as_dir$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+  done
+IFS=$as_save_IFS
+
+  ;;
+esac ;;
+esac
+fi
+PKG_CONFIG=$ac_cv_path_PKG_CONFIG
+if test -n "$PKG_CONFIG"; then
+  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: $PKG_CONFIG" >&5
+printf "%s\n" "$PKG_CONFIG" >&6; }
+else
+  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: no" >&5
+printf "%s\n" "no" >&6; }
+fi
+
+
+  fi
+
+  mmdb_found_pkg_config=no
+  if test "x$PKG_CONFIG" != x; then
+    { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for MaxMindDB via pkg-config" >&5
+printf %s "checking for MaxMindDB via pkg-config... " >&6; }
+    if $PKG_CONFIG --exists libmaxminddb 2>/dev/null; then
+      MMDB_CFLAGS=`$PKG_CONFIG --cflags libmaxminddb`
+      MMDB_LDFLAGS=`$PKG_CONFIG --libs libmaxminddb`
+      mmdb_found_pkg_config=yes
+      { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: yes ($MMDB_CFLAGS $MMDB_LDFLAGS)" >&5
+printf "%s\n" "yes ($MMDB_CFLAGS $MMDB_LDFLAGS)" >&6; }
+    else
+      { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: no" >&5
+printf "%s\n" "no" >&6; }
+    fi
+  fi
+
+  if test "x$mmdb_found_pkg_config" = xyes; then
+        save_CFLAGS=$CFLAGS
+    save_LIBS=$LIBS
+    CFLAGS="$CFLAGS $MMDB_CFLAGS"
+    LIBS="$LIBS $MMDB_LDFLAGS"
+
+    ac_fn_c_check_func "$LINENO" "MMDB_lookup_string" "ac_cv_func_MMDB_lookup_string"
+if test "x$ac_cv_func_MMDB_lookup_string" = xyes
+then :
+
+      ac_fn_c_check_func "$LINENO" "MMDB_get_value" "ac_cv_func_MMDB_get_value"
+if test "x$ac_cv_func_MMDB_get_value" = xyes
+then :
+
+        enable_mmdb="yes"
+
+fi
+
+
+fi
+
+
+    LIBS=$save_LIBS
+    CFLAGS=$save_CFLAGS
+  fi
+
+  if test "x$enable_mmdb" != xyes; then
 
 # Check whether --with-mmdb was given.
 if test ${with_mmdb+y}
@@ -8767,7 +8860,7 @@ esac
 fi
 
 
-  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for MaxMindDB includes" >&5
+    { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for MaxMindDB includes" >&5
 printf %s "checking for MaxMindDB includes... " >&6; }
 
 # Check whether --with-mmdb-includes was given.
@@ -8779,14 +8872,14 @@ else case e in #(
 esac
 fi
 
-  unet_cv_with_mmdb_inc_prefix=$base_mmdb_inc
-  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: $unet_cv_with_mmdb_inc_prefix" >&5
+    unet_cv_with_mmdb_inc_prefix=$base_mmdb_inc
+    { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: $unet_cv_with_mmdb_inc_prefix" >&5
 printf "%s\n" "$unet_cv_with_mmdb_inc_prefix" >&6; }
 
 printf "%s\n" "#define MMDB_INCLUDES_PATH \"$base_mmdb_inc\"" >>confdefs.h
 
 
-  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for MaxMindDB libraries" >&5
+    { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for MaxMindDB libraries" >&5
 printf %s "checking for MaxMindDB libraries... " >&6; }
 
 # Check whether --with-mmdb-libs was given.
@@ -8798,20 +8891,20 @@ else case e in #(
 esac
 fi
 
-  unet_cv_with_mmdb_prefix=$base_mmdb_lib
-  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: $unet_cv_with_mmdb_prefix" >&5
+    unet_cv_with_mmdb_prefix=$base_mmdb_lib
+    { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: $unet_cv_with_mmdb_prefix" >&5
 printf "%s\n" "$unet_cv_with_mmdb_prefix" >&6; }
 
 printf "%s\n" "#define MMDB_LIBS_PATH \"$unet_cv_with_mmdb_prefix\"" >>confdefs.h
 
 
-  save_CFLAGS=$CFLAGS
-  save_LIBS=$LIBS
+    save_CFLAGS=$CFLAGS
+    save_LIBS=$LIBS
 
-  CFLAGS="-I$unet_cv_with_mmdb_inc_prefix"
-  LIBS="-L$unet_cv_with_mmdb_prefix"
+    CFLAGS="-I$unet_cv_with_mmdb_inc_prefix"
+    LIBS="-L$unet_cv_with_mmdb_prefix"
 
-         for ac_header in $unet_cv_with_mmdb_inc_prefix/maxminddb.h
+           for ac_header in $unet_cv_with_mmdb_inc_prefix/maxminddb.h
 do :
   as_ac_Header=`printf "%s\n" "ac_cv_header_$ac_header" | sed "$as_sed_sh"`
 ac_fn_c_check_header_compile "$LINENO" "$ac_header" "$as_ac_Header" "$ac_includes_default"
@@ -8821,7 +8914,7 @@ then :
 #define `printf "%s\n" "HAVE_$ac_header" | sed "$as_sed_cpp"` 1
 _ACEOF
 
-    { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for MMDB_lookup_string in -lmaxminddb" >&5
+      { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for MMDB_lookup_string in -lmaxminddb" >&5
 printf %s "checking for MMDB_lookup_string in -lmaxminddb... " >&6; }
 if test ${ac_cv_lib_maxminddb_MMDB_lookup_string+y}
 then :
@@ -8867,7 +8960,7 @@ printf "%s\n" "$ac_cv_lib_maxminddb_MMDB_lookup_string" >&6; }
 if test "x$ac_cv_lib_maxminddb_MMDB_lookup_string" = xyes
 then :
 
-      { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for MMDB_get_value in -lmaxminddb" >&5
+        { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for MMDB_get_value in -lmaxminddb" >&5
 printf %s "checking for MMDB_get_value in -lmaxminddb... " >&6; }
 if test ${ac_cv_lib_maxminddb_MMDB_get_value+y}
 then :
@@ -8913,8 +9006,9 @@ printf "%s\n" "$ac_cv_lib_maxminddb_MMDB_get_value" >&6; }
 if test "x$ac_cv_lib_maxminddb_MMDB_get_value" = xyes
 then :
 
-        enable_mmdb="yes";
-        MMDB_LDFLAGS="-lmaxminddb"
+          enable_mmdb="yes";
+          MMDB_CFLAGS="-I$unet_cv_with_mmdb_inc_prefix"
+          MMDB_LDFLAGS="-L$unet_cv_with_mmdb_prefix -lmaxminddb"
 
 fi
 
@@ -8926,23 +9020,24 @@ fi
 
 done
 
-  LIBS=$save_LIBS
-  CFLAGS=$save_CFLAGS
+    LIBS=$save_LIBS
+    CFLAGS=$save_CFLAGS
+  fi
 
   if test "x$enable_mmdb" = xyes; then
 
 printf "%s\n" "#define USE_MMDB /**/" >>confdefs.h
 
-    LIBS="$LIBS -L$unet_cv_with_mmdb_prefix $MMDB_LDFLAGS"
-    CFLAGS="$CFLAGS -I$unet_cv_with_mmdb_inc_prefix"
+    LIBS="$LIBS $MMDB_LDFLAGS"
+    CFLAGS="$CFLAGS $MMDB_CFLAGS"
   else
      { printf "%s\n" "$as_me:${as_lineno-$LINENO}: WARNING: Unable to find MaxMindDB, MaxMindDB features will not work without libmaxminddb. Disabling MaxMindDB support." >&5
 printf "%s\n" "$as_me: WARNING: Unable to find MaxMindDB, MaxMindDB features will not work without libmaxminddb. Disabling MaxMindDB support." >&2;}
   fi
 fi
 
-{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking whether to enable libmdbx for storage support" >&5
-printf %s "checking whether to enable libmdbx for storage support... " >&6; }
+{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking whether to enable libmdbx storage support" >&5
+printf %s "checking whether to enable libmdbx storage support... " >&6; }
 # Check whether --enable-mdbx was given.
 if test ${enable_mdbx+y}
 then :
@@ -9086,8 +9181,8 @@ printf "%s\n" "#define USE_MDBX /**/" >>confdefs.h
     LIBS="$LIBS -L$unet_cv_with_mdbx_prefix $MDBX_LDFLAGS"
     CFLAGS="$CFLAGS -I$unet_cv_with_mdbx_inc_prefix"
   else
-     { printf "%s\n" "$as_me:${as_lineno-$LINENO}: WARNING: Unable to find libmdbx, chathistory features will not work without libmdbx. Disabling libmdbx support." >&5
-printf "%s\n" "$as_me: WARNING: Unable to find libmdbx, chathistory features will not work without libmdbx. Disabling libmdbx support." >&2;}
+     { printf "%s\n" "$as_me:${as_lineno-$LINENO}: WARNING: Unable to find libmdbx, chathistory/metadata/webpush features will not work without libmdbx. Disabling libmdbx support." >&5
+printf "%s\n" "$as_me: WARNING: Unable to find libmdbx, chathistory/metadata/webpush features will not work without libmdbx. Disabling libmdbx support." >&2;}
   fi
 fi
 
